### ISSUE TITLE
Write docs for WP Node plugin

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsNodeWP#2]
https://docs.murmurations.network/developers/wp-node.html

**Comment by mediaformat** [comment]
We should add a readme.md for this project.

**Comment by mediaformat** [comment]
I've generated a readme.txt/readme.md from https://tools.wedevs.com/readme/ and text from the Website.

FYI: Modifications should be made to readme.txt, the grunt action `npm run grunt` will generate a Readme.md from the txt file.
