### ISSUE TITLE
Improve location UI/UX

### ISSUE THREAD

**Issue by mediaformat** [MurmurationsNetwork/MurmurationsNodeWP#7]
The location field and search button function as a lookup to OSM, the results populate the location sub-fields with the 1st result.

It would useful to be able to select a specific result from a list.

**Comment by olisb** [comment]
Good call... we should add some description so the User knows that's what the Search is doing.
Being able to select the result you want would be good - as you suggest
And it would be good to be able to input directly into the fields too, or to overwrite what's prefilled by the search

**Comment by mediaformat** [comment]
Fixed in 0.5.0
